app/pico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^teams/', include('teams.urls', namespace='teams')),
	url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
	url(r'^$', views.index, name='index'),
	url(r'^home$', views.home, name='home'),
] + static(settings.MEDIA_URL.replace('/pico',''), document_root=settings.MEDIA_ROOT) # works on server

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # works locally

app/teams/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<team_id>[0-9]*)/$', views.index, name='index'),
	url(r'^create$', views.create, name='create'),
	url(r'^join$', views.join, name='join'),
    url(r'^invite/(?P<action>(send|accept|decline|cancel))$', views.invite, name='invite'),
    url(r'^join-request/(?P<action>(accept|decline|cancel))$', views.join_request, name='join-request'),
	url(r'^leave$', views.leave, name='leave'),
    url(r'^public$', views.is_public, name='public'),
    url(r'^get$', views.get, name='get'),
	url(r'^autocomplete$', views.TeamAutocomplete.as_view(), name='autocomplete'),
]

app/users/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .forms import EmailValidationOnForgotPassword

from . import views

urlpatterns = [
	url(r'^$', views.view, name='index'),
	url(r'^(?P<user_id>[0-9]*)/$', views.view, name='view'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^edit$', views.edit, name='edit'),
	url(r'^settings$', views.settings, name='settings'),
	url(r'^passwordchange$', views.password_change, name='password_change'),
	url(r'^password/reset/$', password_reset,
		{'template_name': 'users/password_reset/password_reset_form.html',
		 'password_reset_form':EmailValidationOnForgotPassword,
		'email_template_name': 'users/password_reset/password_reset_email.html',
		'post_reset_redirect' : reverse_lazy('users:password_reset_done')},
		name="password_reset"),
	url(r'^password/reset/done/$', password_reset_done,
		{'template_name': 'users/password_reset/password_reset_done.html'},
		name='password_reset_done'),
	url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		password_reset_confirm,
		{'template_name': 'users/password_reset/password_reset_confirm.html',
		'post_reset_redirect' : reverse_lazy('users:password_done')},
		name='password_reset_confirm'),
	url(r'^password/done/$',
		password_reset_complete,
		{'template_name': 'users/password_reset/password_reset_complete.html'},
		name='password_done'),
	url(r'^autocomplete$', views.UserAutocomplete.as_view(), name='autocomplete'),
]

app/teams/models.py
from django.db import models

from users.models import User

class Team(models.Model):
    name = models.CharField(max_length=32, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    members = models.ManyToManyField(User, related_name='teams')
    public = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Invite(models.Model):
    team = models.ForeignKey(Team, related_name='invites')
    user = models.ForeignKey(User, related_name='team_invites')
    timestamp = models.DateTimeField(auto_now_add=True)

class JoinRequest(models.Model):
    team = models.ForeignKey(Team, related_name='join_requests')
    user = models.ForeignKey(User, related_name='team_join_requests')
    timestamp = models.DateTimeField(auto_now_add=True)

app/teams/forms.py
from django import forms
from django.urls import reverse_lazy
from dal import autocomplete

from .models import Team, JoinRequest, Invite

class TeamForm(forms.ModelForm):
	name = forms.CharField(required=True)

	class Meta:
		model = Team
		fields = ('name',)

class TeamSelectForm(forms.ModelForm):
	team = forms.ModelChoiceField(queryset=Team.objects.all())

	class Meta:
		model = Team
		fields = ('team',)

class TeamSearchForm(forms.ModelForm):
	team = forms.ModelChoiceField(queryset=Team.objects.all(),
		widget=autocomplete.ModelSelect2(
			url=reverse_lazy('teams:autocomplete'),
			attrs={
				'data-placeholder': 'Search',
			})
	)

	class Meta:
		model = Team
		fields = ('team',)

class JoinRequestForm(forms.ModelForm):
	join_request = forms.ModelChoiceField(queryset=JoinRequest.objects.all())

	class Meta:
		model = JoinRequest
		fields = ('join_request',)

class InviteForm(forms.ModelForm):
	invite = forms.ModelChoiceField(queryset=Invite.objects.all())

	class Meta:
		model = Invite
		fields = ('invite',)

app/teams/views.py
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse

from dal import autocomplete

from .models import Team, Invite, JoinRequest
from .forms import TeamForm, TeamSelectForm, TeamSearchForm, InviteForm, JoinRequestForm
from alerts.models import Alert, Target
from users.forms import UserSearchForm

@login_required
def index(request, team_id=None):
    current = None
    if team_id is not None:
        if Team.objects.filter(id=team_id).exists():
            current = Team.objects.get(id=team_id)
        else:
            return redirect(reverse('teams:index'))

    return render(
        request,
        'teams/index.html',
        {
            'current': current,
            'teams': request.user.teams.all(),
            'team_form': TeamForm(),
            'team_search_form': TeamSearchForm(),
            'user_search_form': UserSearchForm(),
        },
    )

@login_required
def create(request):
    if request.method == 'POST':
        team_form = TeamForm(data=request.POST)

        if team_form.is_valid():
            team = team_form.save()
            team.members.add(request.user)
            data = {
                'tab': render_to_string('teams/team-tab.html', {'team': team}, request),
                'panel': render_to_string('teams/team-panel.html', {'team': team, 'user_search_form': UserSearchForm()}, request),
            }
            return JsonResponse(data, status=200)
    
        else:
            data = {
                'form': render_to_string('forms/horizontal.html', {'form': team_form}, request),
            }
            return JsonResponse(data, status=201)

    return redirect(reverse('teams:index'))

@login_required
def join(request):
    if request.method == 'POST':
        team_select_form = TeamSelectForm(data=request.POST)

        if team_select_form.is_valid():
            team = team_select_form.cleaned_data['team']

            if request.user not in team.members.all():
                if team.public or Invite.objects.filter(team=team, user=request.user).exists():
                    team.members.add(request.user)
                    Invite.objects.filter(team=team, user=request.user).delete()
                    JoinRequest.objects.filter(team=team, user=request.user).delete()
                else:
                    JoinRequest(team=team, user=request.user).save()

            return redirect(reverse('teams:index', kwargs={'team_id':team.id}))

    return redirect(reverse('teams:index'))

@login_required
def invite(request, action):
    if request.method == 'POST':
        if action == 'send':
            team_select_form = TeamSelectForm(data=request.POST)
            user_select_form = UserSearchForm(data=request.POST)

            if team_select_form.is_valid() and user_select_form.is_valid():
                team = team_select_form.cleaned_data['team']
                user = user_select_form.cleaned_data['user']

                if request.user in team.members.all():
                    if user in team.members.all():
                        # User already on team
                        pass
                    elif Invite.objects.filter(team=team, user=user).exists():
                        # Invite already exists
                        pass
                    else:
                        invite = Invite(team=team, user=user); invite.save()
                        alert = Alert(
                            user=user,
                            subject='New Team Invite',
                            body='You have been invited to join team <em>%s</em>.'%(team.name),
                            target=Target.objects.get_or_create(invite=invite)[0]).save()
                else:
                    # User does not have permission to send invite
                    pass    
            
                return redirect(reverse('teams:index', kwargs={'team_id':team.id}))            

        elif action == 'accept':
            return join(request)

        elif action == 'decline':
            team_select_form = TeamSelectForm(data=request.POST)

            if team_select_form.is_valid():
                team = team_select_form.cleaned_data['team']

                if Invite.objects.filter(team=team, user=request.user).exists():
                    Invite.objects.filter(team=team, user=request.user).delete()

                return redirect(reverse('teams:index', kwargs={'team_id':team.id}))

        elif action == 'cancel':
            invite_form = InviteForm(data=request.POST)

            if invite_form.is_valid():
                invite = invite_form.cleaned_data['invite']

                if request.user in invite.team.members.all():
                    invite.delete()

                return redirect(reverse('teams:index', kwargs={'team_id':invite.team.id}))

    return redirect(reverse('teams:index'))

@login_required
def join_request(request, action):
    if request.method == 'POST':
        join_request_form = JoinRequestForm(data=request.POST)

        if join_request_form.is_valid():
            join_request = join_request_form.cleaned_data['join_request']

            if request.user in join_request.team.members.all():
                if action == 'accept':
                    join_request.team.members.add(join_request.user)
                    join_request.delete()
                    Invite.objects.filter(team=join_request.team, user=join_request.user).delete()
                elif action == 'decline':
                    join_request.delete()
            elif request.user == join_request.user and action == 'cancel':
                join_request.delete()

            return redirect(reverse('teams:index', kwargs={'team_id':join_request.team.id}))

    return redirect(reverse('teams:index'))

@login_required
def is_public(request):
    if request.method == 'POST':
        team_select_form = TeamSelectForm(data=request.POST)

        if team_select_form.is_valid():
            team = team_select_form.cleaned_data['team']

            if request.POST.get('public', 'off') == 'on':
                team.public = True
            else:
                team.public = False
            team.save()

            return JsonResponse({'public': team.public})

    return redirect(reverse('teams:index'))

@login_required
def leave(request):
    if request.method == 'POST':
        team_select_form = TeamSelectForm(data=request.POST)

        if team_select_form.is_valid():
            team = team_select_form.cleaned_data['team']
            team.members.remove(request.user)
            if team.members.count() == 0:
                team.delete()
            return JsonResponse({}, status=200)

    return redirect(reverse('teams:index'))

@login_required
def get(request):
    if request.method == 'POST':
        team_search_form = TeamSearchForm(data=request.POST)

        if team_search_form.is_valid():
            team = team_search_form.cleaned_data['team']
            data = {
                'tab': render_to_string('teams/team-tab.html', {'team': team}, request),
                'panel': render_to_string('teams/team-panel.html', {'team': team, 'user_search_form': UserSearchForm()}, request),
            }
            return JsonResponse(data, status=200)

        return JsonResponse({}, status=201)

    return redirect(reverse('teams:index'))

class TeamAutocomplete(autocomplete.Select2QuerySetView):

    def get_queryset(self):     
        if not self.request.user.is_authenticated():
            return Team.objects.none()
        
        qs = Team.objects.all()
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        
        return qs

app/templates/teams/index.html
{% extends 'pico/home.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title_block %}{{ block.super }}{% endblock %}

{% block head_block %}

    {{ block.super }}

    <!-- Team Search CSS -->
    {{ team_search_form.media.css }}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <style>
        #team-search-form .select2-container {
            min-width: 0;
            width: 100% !important;
        }
    </style>

    <!-- Team Panel CSS -->
    <style>
        .team-panel .header {
            display: flex;
            margin-bottom: 10px;
        }
        .team-panel .header h2 {
            float: left;
            margin: 0;
            margin-right: 25px;
        }
        .team-panel .header form {
            margin-top: auto;
            margin-bottom: auto;
        }
        .team-panel .content .panel-heading {
            cursor: pointer;
        }
    </style>

    <!-- User Search CSS -->
    {{ user_search_form.media.css }}

    <!-- Bootstrap Toggle CSS -->
    <link href="{% static 'bootstrap-toggle/css/bootstrap-toggle.min.css' %}" rel="stylesheet">

{% endblock %}

{% block content_block %}

    <div class="row">
        <ul class="nav col-md-2 col-sm-3" id="side-menu">
            <!-- New team -->
            <div class="text-center" style="padding-bottom:15px">
                <a href="#" data-toggle="modal" data-target="#create-team" class="btn btn-default"><i class="fa fa-plus"></i> New Team</a>
            </div>
            
            <!-- Team search -->
            <div class="text-center" style="padding-bottom:15px">
                <form id="team-search-form" method="post" action="{% url 'teams:get' %}">
                    {% csrf_token %}
                    {{ team_search_form.team }}
                </form>
            </div>
            
            <!-- Team tabs -->
            <ul class="nav nav-pills nav-stacked" id="team-tabs">
                <li class="hidden {% if not teams %}active{% endif %}"><a href="#no-teams" data-toggle="pill"></a></li>
                {% for team in teams %}
                    {% if current is None %}
                        {% include 'teams/team-tab.html' with team=team active=forloop.first %}
                    {% elif team == current %}
                        {% include 'teams/team-tab.html' with team=team active=True %}
                    {% else %}
                        {% include 'teams/team-tab.html' with team=team active=False %}
                    {% endif %}
                {% endfor %}
            </ul>
        </ul>

        <!-- Create Team Modal -->
        <div class="modal fade" id="create-team" role="dialog">
            <div class="modal-dialog">
                <form class="form form-horizontal" id="team-form" method="post" action="{% url 'teams:create' %}" enctype="multipart form-data">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">New Team</h4>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}
                        <div id="team-form-contents">
                        {% bootstrap_form team_form layout='horizontal' %}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                <!-- /.modal-content -->
                </form>
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /#create-team -->

        <!-- Tab panes -->
        <div class="tab-content col-md-10 col-sm-9" id="team-panels">
            <div class="tab-pane {% if not teams and current is None %}active{% endif %}" id="no-teams">
                <h1>Well this is awkward!</h1>
                <p>You are not on any teams. Try joining one or creating your own.</p>
            </div>
            {% for team in teams %}
                {% if current is None %}
                    {% include 'teams/team-panel.html' with team=team active=forloop.first %}
                {% elif team == current %}
                    {% include 'teams/team-panel.html' with team=team active=True %}
                {% else %}
                    {% include 'teams/team-panel.html' with team=team active=False %}
                {% endif %}
            {% endfor %}
            {% if current is not None and current not in teams %}
                {% include 'teams/team-panel.html' with team=current active=True %}
            {% endif %}
        </div>
        <!-- /.tab-content -->
    </div>
    <!-- /.row -->

{% endblock %}

{% block foot_block %}
    
    {{ block.super }}

    <!-- Bootstrap Toggle JavaScript -->
    <script src="{% static 'bootstrap-toggle/js/bootstrap-toggle.min.js' %}"></script>
    <script src="{% static 'js/team-public-toggle.js' %}"></script>

    <!-- Team Search JavaScript -->
    {{ team_search_form.media.js }}
    <script src="{% static 'js/team-search.js' %}"></script>

    <!-- Create Team JavaScript -->
    <script src="{% static 'js/team-create.js' %}"></script>

    <!-- Leave Team JavaScript -->
    <script src="{% static 'js/team-leave.js' %}"></script>

    <!-- Team Invite JavaScript -->
    <script src="{% static 'js/team-invite.js' %}"></script>

    <!-- Stickytabs JavaScript -->
    <script src="{% static 'js/team-stickytabs.js' %}"></script>

    <!-- User Search JavaScript -->
    {{ user_search_form.media.js }}

{% endblock %}

app/templates/teams/team-panel.html
{% load team_extras %}

<div class="tab-pane team-panel {% if active %}active{% endif %}" id="team-{{ team.id }}">
    <div class="row header col-md-12">
        <h2>Team {{ team.name }}</h2>

        {% if team in request.user.teams.all %}
            <form class="form form-horizontal team-leave-form"  method="post" action="{% url 'teams:leave' %}" enctype="multipart form-data">
                {% csrf_token %}
                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                <button type="submit" class="btn btn-xs btn-danger">Leave</button>
            </form>
            <!-- /#team-leave-form -->
            <form class="form form-horizontal team-public-form"  method="post" action="{% url 'teams:public' %}" enctype="multipart form-data" style="margin-left:10px;">
                {% csrf_token %}
                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                <input type="checkbox" name="public" {% if team.public %}checked{% endif %} data-toggle="toggle" data-size="mini" data-on="Public" data-off="Private">
            </form>
            <!-- /#team-leave-form -->
        {% elif request.user|has_invite:team %}
            <form class="form form-horizontal team-join-form"  method="post" action="{% url 'teams:invite' action='accept' %}" enctype="multipart form-data">
                {% csrf_token %}
                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                <button type="submit" class="btn btn-xs btn-success">Accept Invite</button>
            </form>
            <!-- /#team-join-form -->
            <form class="form form-horizontal team-invite-decline-form"  method="post" action="{% url 'teams:invite' action='decline' %}" enctype="multipart form-data"  style="margin-left:10px;">
                {% csrf_token %}
                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                <button type="submit" class="btn btn-xs btn-danger">Decline Invite</button>
            </form>
            <!-- /#team-leave-form -->
        {% elif team.public %}
            <form class="form form-horizontal team-join-form"  method="post" action="{% url 'teams:join' %}" enctype="multipart form-data">
                {% csrf_token %}
                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                <button type="submit" class="btn btn-xs btn-success">Join</button>
            </form>
            <!-- /#team-join-form -->
        {% elif team|has_request:request.user %}
            <form class="form form-horizontal cancel-join-request-form" method="post" action="{% url 'teams:join-request' 'cancel' %}" enctype="multipart form-data">
                {% csrf_token %}
                <input type="hidden" id="id_request" name="request" value="{% with team|get_request:user as join_request %}{{ join_request.id }}{% endwith %}"/>
                <button type="submit" class="btn btn-default btn-xs">Cancel Join Request</button>
            </form>
        {% else %}
            <form class="form form-horizontal team-join-form"  method="post" action="{% url 'teams:join' %}" enctype="multipart form-data">
                {% csrf_token %}
                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                <button type="submit" class="btn btn-xs btn-success">Send Join Request</button>
            </form>
            <!-- /#team-join-form -->
        {% endif %}
    </div>
    <!-- /.header -->

    <div class="row content">
        <div class="col-md-7">
            <div class="panel panel-default" id="panel1">
                <div class="panel-heading" data-toggle="collapse" data-target="#team-{{team.id}}-members">
                    <h4 class="panel-title">Members</h4>
                </div>
                <div id="team-{{team.id}}-members" class="panel-collapse collapse in">
                    {% if team.members.all %}
                        <div class="list-group">
                            {% for member in team.members.all %}
                                <a href="{% url 'users:view' member.id %}" class="list-group-item">
                                    {{ member.username }}
                                </a>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="list-group"><div class="list-group-item">No members</div></div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if request.user in team.members.all %}
            <div class="col-md-5">
                
                <div class="panel panel-default" id="panel1">
                    <div class="panel-heading" data-toggle="collapse" data-target="#team-{{team.id}}-requests">
                        <h4 class="panel-title">Join Requests</h4>
                    </div>
                    <div id="team-{{team.id}}-requests" class="panel-collapse collapse in">
                        {% if team.join_requests.all %}
                            <div class="list-group">
                                {% for join_request in team.join_requests.all %}
                                    <a href="{% url 'users:view' join_request.user.id %}" class="list-group-item">
                                        {{ join_request.user.username }}
                                        <div class="pull-right input-group" style="top:-10px">

                                            <form style="display:inline" class="form accept-join-request-form" method="post" action="{% url 'teams:join-request' 'accept' %}" enctype="multipart form-data">
                                                {% csrf_token %}
                                                <input type="hidden" id="id_request" name="request" value="{{ join_request.id }}"/>
                                                <button type="submit" class="btn btn-link" style="padding-left:0;padding-right:0;padding-top:5px;padding-bottom:4px;margin-right:5px;"><i class="fa fa-check fa-2x"></i></button>
                                            </form>
                                            <!-- /#accept-join-request-form -->

                                            <form style="display:inline" class="form decline-join-request-form" method="post" action="{% url 'teams:join-request' action='decline' %}" enctype="multipart form-data">
                                                {% csrf_token %}
                                                <input type="hidden" id="id_request" name="request" value="{{ join_request.id }}"/>
                                                <button type="submit" class="btn btn-link" style="padding-left:0;padding-right:0;padding-top:5px;padding-bottom:4px;"><i class="fa fa-times fa-2x"></i></button>
                                            </form>
                                            <!-- /#decline-join-request-form -->

                                        </div>
                                    </a>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="list-group"><div class="list-group-item">No pending requests</div></div>
                        {% endif %}
                    </div>
                </div>
                <!-- ./join-requests -->

                <div class="panel panel-default" id="panel1">
                    <div class="panel-heading" data-toggle="collapse" data-target="#team-{{team.id}}-invites">
                        <h4 class="panel-title" style="display:inline;margin-right:4px;">Invites</h4>
                        <a href="#" class="small" data-toggle="modal" data-target="#new-invite-team-{{team.id}}">New</a>
                    </div>
                    <div id="team-{{team.id}}-invites" class="panel-collapse collapse in">
                        {% if team.invites.all %}
                            <div class="list-group">
                                {% for invite in team.invites.all %}
                                    <a href="{% url 'users:view' invite.user.id %}" class="list-group-item">
                                        {{ invite.user.username }}
                                        <div class="pull-right input-group" style="top:-10px;">

                                            <form style="display:inline" class="form cancel-invite-form" method="post" action="{% url 'teams:invite' action='cancel' %}" enctype="multipart form-data">
                                                {% csrf_token %}
                                                <input type="hidden" id="id_invite" name="invite" value="{{ invite.id }}"/>
                                                <button type="submit" class="btn btn-link" style="padding-left:0;padding-right:0;padding-top:5px;padding-bottom:4px;"><i class="fa fa-times fa-2x"></i></button>
                                            </form>
                                            <!-- /#cancel-invite-form -->

                                        </div>
                                    </a>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="list-group"><div class="list-group-item">No pending invites</div></div>
                        {% endif %}
                    </div>
                </div>
                <!-- ./invites -->

                <!-- Send Invite Modal -->
                <div class="modal fade" id="new-invite-team-{{team.id}}" role="dialog">
                    <div class="modal-dialog">
                        <form class="form form-horizontal" id="team-form" method="post" action="{% url 'teams:invite' action='send' %}" enctype="multipart form-data">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">New Invite</h4>
                            </div>
                            <div class="modal-body">
                                {% csrf_token %}
                                <input type="hidden" id="id_team" name="team" value="{{ team.id }}"/>
                                {{ user_search_form.user }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" data-dismiss="modal" class="btn">Cancel</button>
                                <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                        </form>
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /#new-invite -->

            </div>
        {% endif %}

    </div>
    <!-- /.content -->
</div>

app/templates/teams/team-tab.html
<li class="team-tab {% if active %}active{%endif%}"><a href="#team-{{ team.id }}" data-toggle="pill">{{ team.name }}</a></li>