app/pico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^teams/', include('teams.urls', namespace='teams')),
	url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
	url(r'^$', views.index, name='index'),
	url(r'^home$', views.home, name='home'),
] + static(settings.MEDIA_URL.replace('/pico',''), document_root=settings.MEDIA_ROOT) # works on server

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # works locally

app/users/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .forms import EmailValidationOnForgotPassword

from . import views

urlpatterns = [
	url(r'^$', views.view, name='index'),
	url(r'^(?P<user_id>[0-9]*)/$', views.view, name='view'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^edit$', views.edit, name='edit'),
	url(r'^settings$', views.settings, name='settings'),
	url(r'^passwordchange$', views.password_change, name='password_change'),
	url(r'^password/reset/$', password_reset,
		{'template_name': 'users/password_reset/password_reset_form.html',
		 'password_reset_form':EmailValidationOnForgotPassword,
		'email_template_name': 'users/password_reset/password_reset_email.html',
		'post_reset_redirect' : reverse_lazy('users:password_reset_done')},
		name="password_reset"),
	url(r'^password/reset/done/$', password_reset_done,
		{'template_name': 'users/password_reset/password_reset_done.html'},
		name='password_reset_done'),
	url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		password_reset_confirm,
		{'template_name': 'users/password_reset/password_reset_confirm.html',
		'post_reset_redirect' : reverse_lazy('users:password_done')},
		name='password_reset_confirm'),
	url(r'^password/done/$',
		password_reset_complete,
		{'template_name': 'users/password_reset/password_reset_complete.html'},
		name='password_done'),
	url(r'^autocomplete$', views.UserAutocomplete.as_view(), name='autocomplete'),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import User as AuthUser

class User(AuthUser):
    def get_profile(self):
        if hasattr(self, 'profile') and self.profile is not None:
            return self.profile
        profile = UserProfile()
        profile.user = self
        return profile

    class Meta:
        proxy = True
        permissions = (
            ('create_contest', 'Can create contests'),
        )

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    theme = models.URLField(null=True)

app/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy

from dal import autocomplete

from .models import User

class UserForm(UserCreationForm):
	username = forms.CharField(required=True)
	password2 = forms.CharField(label="Confirmation", widget=forms.PasswordInput,
		help_text="Enter the same password as above.")
	first_name = forms.CharField(required=False)
	last_name = forms.CharField(required=False)
	email = forms.CharField(required=False)

	class Meta:
		model = User
		fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')

class LoginForm(AuthenticationForm):
	# See https://docs.djangoproject.com/en/1.10/topics/auth/default/#django.contrib.auth.forms.AuthenticationForm
	pass

class UserSelectForm(forms.ModelForm):
	user = forms.ModelChoiceField(queryset=User.objects.all())

	class Meta:
		model = User
		fields = ('user',)

class UserSearchForm(forms.ModelForm):
	user = forms.ModelChoiceField(queryset=User.objects.all(),
		widget=autocomplete.ModelSelect2(
			url=reverse_lazy('users:autocomplete'),
			attrs={
				'data-placeholder': 'User',
			})
	)

	class Meta:
		model = User
		fields = ('user',)

class EmailValidationOnForgotPassword(PasswordResetForm):
	def clean_email(self):
		email = self.cleaned_data['email']
		if not User.objects.filter(email__iexact=email, is_active=True).exists():
			raise ValidationError("There is no user registered with the sepcified email address!")
		return email


app/users/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator, validate_email
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from dal import autocomplete

from common.decorators import anonymous_required
from .forms import UserForm, LoginForm
from .lib import storage
from .models import User


@login_required
def view(request, user_id=None):
    user = None
    if user_id is not None:
        if User.objects.filter(id=user_id).exists():
            user = User.objects.get(id=user_id)
        else:
            return redirect(reverse('users:index'))

    return render(
        request,
        'users/index.html',
        {
            'user': user,
        },
    )

@anonymous_required
def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)

            return redirect(reverse('home'))
    else:
        user_form = UserForm()

    return render(
        request,
        'users/register.html',
        {'user_form': user_form})

@anonymous_required
def login(request):
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)

        if login_form.is_valid():
            auth_login(request, login_form.user_cache)
            return redirect(reverse('home'))

    else:
        login_form = LoginForm()

    return render(
        request,
        'users/login.html',
        {'login_form': login_form})

def logout(request):
    if request.user.is_authenticated():
        auth_logout(request)
    return redirect(reverse('index'))

@login_required
def edit(request):
    if request.method == 'POST':

        if 'username' in request.POST:
            username = request.POST.get('username')
            # Check if username is taken
            if User.objects.filter(username=username).exclude(pk=request.user.pk).exists():
                return JsonResponse({'error': 'Username already in use.'}, status=201)
            try:
                UnicodeUsernameValidator()(username)
                request.user.username = username
                request.user.save()
                return JsonResponse({'val':username}, status=200)
            except ValidationError as err:
                return JsonResponse({'error': '; '.join(err.messages)}, status=201)

        if 'first_name' in request.POST:
            request.user.first_name = request.POST.get('first_name')
            request.user.save()
            return JsonResponse({'val':request.user.first_name}, status=200)

        if 'last_name' in request.POST:
            request.user.last_name = request.POST.get('last_name')
            request.user.save()
            return JsonResponse({'val':request.user.last_name}, status=200)

        if 'email' in request.POST:
            email = request.POST.get('email')
            if not email:
                request.user.email = email
                request.user.save()
                return JsonResponse({'val':email}, status=200)
            else:
                try:
                    validate_email(email)
                    request.user.email = email
                    request.user.save()
                    return JsonResponse({'val':email}, status=200)
                except ValidationError as err:
                    return JsonResponse({'error': '; '.join(err.messages)}, status=201)

        if 'theme' in request.POST:
            theme = request.POST.get('theme')
            
            # Use default
            if not theme:
                profile = request.user.get_profile()
                profile.theme = theme
                profile.save()
                return JsonResponse({'theme': static('bootstrap/css/bootstrap.min.css')}, status=200)
            
            # Use Bootswatch theme
            try:
                URLValidator()(theme)
                if not theme.endswith('.css'):
                    raise ValidationError('URL must refer to a CSS file.')
                profile = request.user.get_profile()
                profile.theme = theme
                profile.save()
                return JsonResponse({'theme': theme}, status=200)
            except ValidationError as err:
                return JsonResponse({'error': '; '.join(err.messages)}, status=201)

        return JsonResponse({}, status=400)

    return redirect(reverse('users:view', kwargs={'user_id':request.user.id}))

@login_required
def settings(request):
    context = {}
    if request.user.is_staff:
        usage_root = storage.usage_root()
        usage_pico = storage.usage_pico()
        usage_db = storage.usage_db()
        context['disk_usage'] = {
            'total': usage_root.total,
            'free': usage_root.free,
            'pico': usage_pico,
            'db': usage_db,
            'other': usage_root.used-usage_pico-usage_db
        }
    return render(request, 'users/settings.html', context)

@login_required
def password_change(request):
    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, data=request.POST)

        if password_change_form.is_valid():
            password_change_form.save()
            update_session_auth_hash(request, password_change_form.user)
            return redirect(reverse('home'))

    else:
        password_change_form = PasswordChangeForm(request.user)

    return render(
        request,
        'users/password_change.html',
        {'password_change_form': password_change_form})

class UserAutocomplete(autocomplete.Select2QuerySetView):

    def get_queryset(self):     
        if not self.request.user.is_authenticated():
            return User.objects.none()
        
        qs = User.objects.all()
        if self.q:
            qs = qs.filter(username__istartswith=self.q)

        return qs

app/templates/users/base.html
{% extends 'pico/index.html' %}

{% block head_block %}
	{{ block.super }}
	<style>
		.form-panel .nav-pills > li {
			width: 100%;
		}
	</style>
{% endblock %}

{% block form_block %}
    <ul class="nav nav-pills">
        <li class="active">
            <a>{% block heading %}{% endblock %}</a>
        </li>
    </ul>

    <div class="tab-content clearfix">
        {% block content_block %}{% endblock %}
    </div>
{% endblock %}

app/templates/users/index.html
{% extends 'pico/home.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title_block %}{{ block.super }}{% endblock %}

{% block head_block %}

    {{ block.super }}

    <style>
        .user-info .input-wrapper {
            overflow: hidden;
            padding-right: 5px;
        }
        .user-info input {
            width: 100%;
        }
        .user-info .btn-save, .user-info .btn-cancel {
            float: right;
        }
        .user-info .input-text {
            display: inline-block;
            padding-top: 7px;
            margin-bottom: 0;
            margin-right: 10px;
            float: left;
        }
        .user-info .btn-edit, .user-info .btn-save, .user-info .btn-cancel {
            padding: 0;
            padding-left: 4px;
            padding-right: 4px;
            margin-top: 5px;
        }
        .user-info form, .user-info .help-block {
            display: none;
        }
        .user-info div.editing form {
            display: inline;
        }
        .user-info div.editing .help-block {
            display: inline-block;
            vertical-align: middle;
        }
        .user-info div.editing .input-text, .user-info div.editing .btn-edit {
            display: none;
        }
    </style>

{% endblock %}

{% block content_block %}

    {% if user == request.user %} 
        <h1>My Profile</h1>
    {% else %}
        <h1>View Profile</h1>
    {% endif %}
    <hr />

    <div class="row">
        <div class="form-horizontal user-info">

            <div class="form-group">
                <label class="control-label col-sm-2" for="username">Username</label>
                <div class="col-md-3 col-sm-4">
                    <span class="input-text">{{ user.username }}</span>
                    
                    {% if user == request.user %}
                        <button class="btn btn-link btn-edit"><i class="fa fa-pencil"></i></button>

                        <form class="user-edit-form" method="post" action="{% url 'users:edit' %}">
                            {% csrf_token %}
                            <button type="button" class="btn btn-link btn-cancel"><i class="fa fa-times"></i></button>
                            <button type="submit" class="btn btn-link btn-save"><i class="fa fa-floppy-o"></i></button>
                            <div class="input-wrapper">
                                <input type="text" class="form-control" id="username" placeholder="Username" name="username" value="{{ user.username }}">
                            </div>
                        </form>
                    {% endif %}
                </div>
                <span class="help-block"></span>
            </div>

            {% if user == request.user %}
                <div class="form-group">
                    <label class="control-label col-sm-2" for="pwd">Password</label>
                    <div class="col-md-3 col-sm-4">
                        <a href="{% url 'users:password_change' %}" class="btn btn-default btn-sm">Change Password</a>
                    </div>
                </div>
            {% endif %}

            <div class="form-group">
                <label class="control-label col-sm-2" for="first_name">First name</label>
                <div class="col-md-3 col-sm-4">
                    <span class="input-text">{% if user.first_name %}{{ user.first_name }}{% else %}(none){% endif %}</span>
                    
                    {% if user == request.user %}
                        <button class="btn btn-link btn-edit"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                        
                        <form class="user-edit-form" method="post" action="{% url 'users:edit' %}">
                            {% csrf_token %}
                            <button type="button" class="btn btn-link btn-cancel"><i class="fa fa-times"></i></button>
                            <button type="submit" class="btn btn-link btn-save"><i class="fa fa-floppy-o"></i></button>
                            <div class="input-wrapper">
                                <input type="text" class="form-control" id="first_name" placeholder="First name" name="first_name" value="{{ user.first_name }}">
                            </div>
                        </form>
                    {% endif %}
                </div>
                <span class="help-block"></span>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="last_name">Last name</label>
                <div class="col-md-3 col-sm-4">
                    <span class="input-text">{% if user.last_name %}{{ user.last_name }}{% else %}(none){% endif %}</span>
                    
                    {% if user == request.user %}
                        <button class="btn btn-link btn-edit"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                        
                        <form class="user-edit-form" method="post" action="{% url 'users:edit' %}">
                            {% csrf_token %}
                            <button type="button" class="btn btn-link btn-cancel"><i class="fa fa-times"></i></button>
                            <button type="submit" class="btn btn-link btn-save"><i class="fa fa-floppy-o"></i></button>
                            <div class="input-wrapper">
                                <input type="text" class="form-control" id="last_name" placeholder="Last name" name="last_name" value="{{ user.last_name }}">
                            </div>
                        </form>
                    {% endif %}
                </div>
                <span class="help-block"></span>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Email</label>
                <div class="col-md-3 col-sm-4">
                    <span class="input-text">{% if user.email %}{{ user.email }}{% else %}(none){% endif %}</span>
                    {% if user == request.user %}
                        <button class="btn btn-link btn-edit"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                        
                        <form class="user-edit-form" method="post" action="{% url 'users:edit' %}">
                            {% csrf_token %}
                            <button type="button" class="btn btn-link btn-cancel"><i class="fa fa-times"></i></button>
                            <button type="submit" class="btn btn-link btn-save"><i class="fa fa-floppy-o"></i></button>
                            <div class="input-wrapper">
                                <input type="text" class="form-control" id="email" placeholder="Email" name="email" value="{{ user.email }}">
                            </div>
                        </form>
                    {% endif %}
                </div>
                <span class="help-block"></span>
            </div>

        </div>
    </div>

{% endblock %}

{% block foot_block %}
    
    {{ block.super }}

    <script src="{% static 'js/user-edit.js' %}"></script>

{% endblock %}

app/templates/users/login.html
{% extends 'users/base.html' %}
{% load bootstrap3 %}

{% block heading %}Login{% endblock %}

{% block content_block %}
	<form class="form form-horizontal" id="login_form" method="post" action="{% url 'users:login' %}">
	    {% csrf_token %}
	    {% bootstrap_form login_form layout='horizontal' %}
	    
	    {% buttons layout='horizontal' %}
	        {% bootstrap_button 'Submit' 'submit' %}
	        {% url 'users:password_reset' as password_reset_url %}
	        {% bootstrap_button 'Forgot password' 'link' href=password_reset_url %}
	    {% endbuttons %}
	</form>

    <div class="hr-faded"></div>

    <div style="text-align:center;">
    	<a href="{% url 'users:register' %}">Create new account</a>
    </div>
{% endblock %}


app/templates/users/password_change.html
{% extends 'pico/home.html' %}
{% load bootstrap3 %}

{% block content_block %}
    <h1>Change Password</h1>
    <hr/>
    <br/>

    <form class="form form-horizontal" id="password_change_form" method="post" action="{% url 'users:password_change' %}">
        {% csrf_token %}
        {% bootstrap_form password_change_form layout='horizontal' %}

        {% buttons layout='horizontal' %}
            {% bootstrap_button 'Submit' 'submit' %}
            {% url 'users:index' user_id=request.user.id as user_url %}
            {% bootstrap_button 'Cancel' 'button' button_class='btn-default' href=user_url %}
        {% endbuttons %}
    </form>
{% endblock %}

app/templates/users/register.html
{% extends 'users/base.html' %}
{% load bootstrap3 %}

{% block heading %}Register{% endblock %}

{% block content_block %}
    <form class="form form-horizontal" id="user_form" method="post" action="{% url 'users:register' %}"
            enctype="multipart/form-data">

        {% csrf_token %}
        {% bootstrap_form user_form layout='horizontal' %}

        {% buttons layout='horizontal' %}
            {% bootstrap_button 'Submit' 'submit' %}
        {% endbuttons %}
    </form>

	<div class="hr-faded"></div>
	
	<div style="text-align:center;">
		<a href="{% url 'users:login' %}">Already have an account</a>
	</div>
{% endblock %}

app/templates/users/settings.html
{% extends 'pico/home.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title_block %}{{ block.super }}{% endblock %}

{% block head_block %}

    {{ block.super }}

    <!-- Header Footer CSS -->
    <style>
        .header {
            display: flex;
            margin-bottom: 10px;
        }
        .header h2 {
            float: left;
            margin: 0;
            margin-right: 25px;
        }
        .header button {
            margin-top: auto;
            margin-bottom: auto;
        }
        .footer {
            padding-bottom: 10px;
        }
    </style>

    <!-- Picker CSS -->
    <style>
        /* Collected from Bootswatch [https://bootswatch.com/] */
        .preview{margin-bottom:4em;background-color:rgba(234,241,241,0.4);}
        .preview .image{position:relative}
        .preview .image:before{box-shadow:inset 0 0 0 1px rgba(0,0,0,.1);position:absolute;top:0;left:0;width:100%;height:100%;content:"";pointer-events:none}
        .preview .options{padding:1em 2em 2em;border:1px solid rgba(0,0,0,.05);border-top:none;text-align:center}
        .preview .options p{margin-bottom:2em}
    </style>

{% endblock %}

{% block content_block %}
    <div class="row">
        <div class="col-md-2 col-sm-3" id="side-menu" style="padding-left:0;">
            <ul class="nav nav-pills nav-stacked stickytabs">
                <li class="active"><a href="#appearance" data-toggle="pill">Appearance</a></li>
                {% if request.user.is_staff %}<li><a href="#storage" data-toggle="pill">Storage</a></li>{% endif %}
            </ul>
        </div>

        <!-- Tab panes -->
        <div class="tab-content col-md-10 col-sm-9" id="team-panels">
            <div class="tab-pane active" id="appearance">
                <form id="change-theme-form" method="post" action="{% url 'users:edit' %}">
                    {% csrf_token %}
                    <input class="hidden" name="theme" id="theme" />
                    
                    <div class="header">
                        <h2>Appearance</h2>
                        <button type="submit" class="btn btn-default" id="default-theme-btn">Use Default</button>
                    </div>
                    <hr />

                    <div class="alert hidden"><h4></h4></div>
                    <div class="row" id="picker"></div>
                    <div class="footer hidden row text-center text-muted" id="acknowledgement">
                        Themes provided by <a href="https://bootswatch.com/">Bootswatch</a>
                    </div>
                </form>
                <!-- /#change-theme-form -->
            </div>
            <!-- /.tab-pane -->

            {% if request.user.is_staff %}
                <div class="tab-pane" id="storage">
                    <div class="header">
                        <h2>Storage</h2>
                    </div>
                    <hr />

                    <div id="disk-usage-chart" style="width:100%; height:400px;"></div>
                    
                    <div class="hidden" id="disk-usage">
                        <var id="total">{{ disk_usage.total }}</var>
                        <var id="free">{{ disk_usage.free }}</var>
                        <var id="pico">{{ disk_usage.pico }}</var>
                        <var id="db">{{ disk_usage.db }}</var>
                        <var id="other">{{ disk_usage.other }}</var>
                    </div>
                </div>
                <!-- /.tab-pane -->
            {% endif %}
        </div>
        <!-- /.tab-content -->
    </div>
    <!-- /.row -->

    

{% endblock %}

{% block foot_block %}
    
    {{ block.super }}

    <!-- Theme Picker JavaScript -->
    <script src="{% static 'js/theme-picker.js' %}"></script>

    <!-- Disk Usage JavaScript -->
    <script src="{% static 'highcharts/highcharts.js' %}"></script>
    <script src="{% static 'js/storage.js' %}"></script>

    <!-- Stickytabs JavaScript -->
    <script src="{% static 'stickytabs/jquery.stickytabs.js' %}"></script>

{% endblock %}