app/contests/urls.py

from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create_contest$', views.createContest, name='create_contest'),
	url(r'^edit/(?P<contest_id>\d+)/$', views.editContest, name='edit_contest'),
	url(r'^delete/(?P<contest_id>\d+)/$', views.deleteContest, name='delete_contest'),
	url(r'^activate/(?P<contest_id>\d+)/$', views.activateContest, name='activate_contest'),
	url(r'^create_template$', views.createTemplate, name='create_template'),
	url(r'^scoreboard/$', views.scoreboard, name='scoreboard'),
	url(r'^contest/(?P<contest_id>\d+)/$', views.displayContest, name='contest'),
	url(r'^contest/(?P<contest_id>\d+)/problemDescription$', views.displayProblemDescription, name='problem_description'),
	url(r'^contest/(?P<contest_id>\d+)/scoreboard$', views.scoreboard, name='scoreboard'),
	url(r'^contest/(?P<contest_id>\d+)/judge$', views.displayAllSubmissions, name='contest_judge_submissions'),
	url(r'^contest/(?P<contest_id>\d+)/judge/(?P<run_id>\d+)/$', views.displayJudge, name='contest_judge'),
	url(r'^contest/(?P<contest_id>\d+)/(?P<team_id>\d+)/submissions$',
		views.displayMySubmissions, name='contest_submissions'),
	url(r'^api/get_notification/$', views.show_notification, name='show_notification'),
	url(r'^api/close_notification/$', views.close_notification, name='close_notification'),
	url(r'^api/refresh_submission/$', views.refresh_submission, name='refresh_submission'),
	url(r'^api/refresh_scoreboard/$', views.refresh_scoreboard, name='refresh_scoreboard'),
]

app/pico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^teams/', include('teams.urls', namespace='teams')),
	url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
	url(r'^$', views.index, name='index'),
	url(r'^home$', views.home, name='home'),
] + static(settings.MEDIA_URL.replace('/pico',''), document_root=settings.MEDIA_ROOT) # works on server

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # works locally

app/v0/contests/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^home$', views.home, name='home'),
	url(r'^diff$', views.diff, name='diff'),
    url(r'^create$', views.create, name='create'),
	url(r'^scoreboard$', views.scoreboard, name='scoreboard')
]

app/contests/models.py
from django.db import models
from django.utils import timezone

from users.models import User
from teams.models import Team

from datetime import datetime, timedelta

class ContestManager(models.Manager):
    """
    Helper method used to fetch all unstarted, active or past contests.
    """
    def unstarted(self):
        unstarted_contests = set()
        for contest in super(ContestManager, self).get_queryset():
            if contest.contest_start is None:
                unstarted_contests.add(contest)
        return unstarted_contests

    def active(self):
        active_contests = set()
        for contest in super(ContestManager, self).get_queryset():
            if contest.contest_start is not None and contest.contest_end() > timezone.now():
                active_contests.add(contest)
        return active_contests

    def past(self):
        past_contests = set()
        for contest in super(ContestManager, self).get_queryset():
            if contest.contest_start is not None and contest.contest_end() <= timezone.now():
                past_contests.add(contest)
        return past_contests


class Contest(models.Model):
    """
    A Contest object has any number of Problem objects associated with it as well as the fields below
    """
    title = models.CharField(max_length=128)
    date_created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name="contest_creator")
    languages = models.CharField(max_length=64)
    contest_length = models.TimeField(null=True, blank=True)
    contest_start = models.DateTimeField(null=True, blank=True)
    time_penalty = models.CharField(max_length=20, null=True, blank=True)
    autojudge_enabled = models.BooleanField(max_length=1, default=False)
    autojudge_review = models.CharField(max_length=128, null=True, blank=True)
    problem_description = models.FileField(upload_to='uploads/', null=True, blank=True)
    contest_admins = models.ManyToManyField(User, related_name="contest_admins", blank=True)
    contest_participants = models.ManyToManyField(Team, related_name="contest_participants", blank=True)

    objects = ContestManager()

    def contest_end(self):
        if self.contest_start is None:
            return datetime.max.replace(tzinfo=timezone.utc)
        return self.contest_start + timedelta(seconds=self.contest_length.hour*3600+self.contest_length.minute*60)

    '''def time_remaining(self):
        if self.contest_start is None:
            return "Not started"
        seconds = (self.contest_end() - timezone.now()).seconds
        return "%d:%02d:%02d remaining"%(seconds//3600, seconds%3600//60, seconds%60)'''

    def __str__(self):
        return self.title


class Problem(models.Model):
    """
    A Problem object has any number of ProblemInput and ProblemSolution objects associated with it as well as the fields below
    """
    name = models.CharField(max_length=2048, null=True, blank=True)
    input_description = models.TextField(null=True, blank=True)
    output_description = models.TextField(null=True, blank=True)
    sample_input = models.FileField(upload_to='uploads/', null=True, blank=True)
    sample_output = models.FileField(upload_to='uploads/', null=True, blank=True)
    contest = models.ForeignKey(Contest, null=True, blank=True, on_delete=models.CASCADE)
    timeout = models.IntegerField(default=5, blank=True)


class ProblemInput(models.Model):
    problem = models.ForeignKey(Problem, related_name = 'problem_input')
    program_input = models.FileField(upload_to='uploads/', null=True, blank=False)


class ProblemSolution(models.Model):
    problem = models.ForeignKey(Problem, related_name = 'problem_solution')
    solution = models.FileField(upload_to='uploads/', null=True, blank=True)


class Participant(models.Model):
    """
    A Participant object is created when a team accept the invitation to participate in a contest.
    """
    contest = models.ForeignKey(Contest, null=True, blank=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, blank=True, on_delete=models.CASCADE)
    score = models.IntegerField


class Submission(models.Model):
    run_id = models.IntegerField(default=0)  # run_id is not the primary key of submission.
                                             # It should be unique within a contest, count start from 1 and increment
                                             # as later submission comes in.
    team = models.ForeignKey(Team, null = True)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, null=True)
    code_file = models.FileField(upload_to='uploads/', null=True, blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    original_filename = models.CharField(max_length=128, null=True, blank=True)

    JUDGE_RESULT = (
        ('YES', 'Yes'),
        ('WRONG', 'Wrong Answer'),
        ('OFE', 'Output Format Error'),
        ('IE', 'Incomplete Error'),
        ('EO', 'Excessive Output'),
        ('CE', 'Compilation Error'),
        ('RTE', 'Run-Time Error'),
        ('TLE', 'Time-Limit Exceeded'),
        ('OTHER', 'Other-Contact Staff'),
    )

    SUBMISSION_STATE_CHOICES = (
        ('NEW', 'New'),
        ('YES', 'Yes'),
        ('NO', 'No'),
    )
    state = models.CharField(max_length=20, choices=SUBMISSION_STATE_CHOICES, default='NEW')
    result = models.CharField(max_length=20, choices=JUDGE_RESULT, null=True)

    def __str__(self):
        return str(self.run_id)


class ContestTemplate(models.Model):
    title = models.CharField(max_length=128)
    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name="contesttemplate_creator")
    languages = models.CharField(max_length=64)
    contest_length = models.TimeField(null=True, blank=True)
    time_penalty = models.CharField(max_length=20, null=True, blank=True)
    autojudge_enabled = models.BooleanField(max_length=1, default=False)
    autojudge_review = models.CharField(max_length=128, null=True, blank=True)
    contest_admins = models.ManyToManyField(User, related_name="contesttemplate_admins", blank=True)
    contest_participants = models.ManyToManyField(Team, related_name="contesttemplate_participants", blank=True)

    def __str__(self):
        return self.title


class Notification(models.Model):
    """
    A Notification object is created when judge return the result of a submission to participant.
    It is deleted when participant close the notification.
    """
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)


class ContestInvite(models.Model):
    """
    A ContestInvite object is created when contest admin add a team as participant of a contest.
    It is deleted when team accept or decline the invitation.
    """
    contest = models.ForeignKey(Contest)
    team = models.ForeignKey(Team)

app/templates/contests/all_submissions.html
{% extends 'contests/base.html' %}

{% load bootstrap3 %}
{% load staticfiles %}
{% load contest_extras %}

{% block title_block %}{{ block.super }}{% endblock %}

{% block head_block %}
    {{ block.super }}
    <style>
        .panel-body {
            padding: 0px;
        }
        .table {
            margin-bottom: 0px;
        }
        .table>tbody>tr>td,
        .table>tbody>tr>th {
            vertical-align: middle;
        }
    </style>
{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'contests:contest' contest_id=contest_data.id %}">{{ contest_data.title }}</a></li>
    <li class="active">Submissions</li>
{% endblock %}

{% block content_block %}
    {{ block.super }}

    <div id="refreshSubmissionUrl" style="display: none;">{% url 'contests:refresh_submission'%}</div>
    <div id="contestId" style="display: none;">{{ contest_data.id }}</div>
    <div id="submission_table">
        <div id="new_submissions" class="panel panel-default panel-table">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapse1">
                <div class="row">
                    <div class="col col-xs-6">
                        <h3 class="panel-title">New Submissions</h3>
                    </div>
                </div>
            </div>
            <div id="collapse1" class="panel-collapse collapse in">
                <table class="table table-striped table-bordered table-list" id="mydata1">
                    <thead>
                        <tr>
                            <th>Run ID</th>
                            <th>Team</th>
                            <th>State</th>
                            <th>Result</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for submission in new_submissions %}
                        <tr>
                            <th>{{ submission.run_id }} </th>
                            <td>{{ submission.team.name }}</td>
                            <td>{{ submission.get_state_display }}</td>
                            <td>{{ submission.get_result_display}}</td>
                            <td><a class="btn btn-default" href="{% url 'contests:contest_judge' contest_data.id submission.run_id %}">Judge</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
               </table>
            </div>
        </div>

        <div id="judged_submissions" class="panel panel-default panel-table">
            <div class="panel-heading" data-toggle="collapse" data-target="#collapse2">
                <div class="row">
                    <div class="col col-xs-6">
                        <h3 class="panel-title">Judged Submissions</h3>
                    </div>
                </div>
            </div>
            <div id="collapse2" class="panel-collapse collapse in">
                <table class="table table-striped table-bordered table-list" id="mydata2">
                    <thead>
                        <tr>
                            <th>Run ID</th>
                            <th>Team</th>
                            <th>State</th>
                            <th>Result</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for submission in judged_submissions %}
                        <tr>
                            <th>{{ submission.run_id }} </th>
                            <td>{{ submission.team.name }}</td>
                            <td>{{ submission.get_state_display }}</td>
                            <td>{{ submission.get_result_display}}</td>
                            <td><a class="btn btn-default" href="{% url 'contests:contest_judge' contest_data.id submission.run_id %}">Judge</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
               </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block foot_block %}
    {{ block.super }}

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script>
    <script src="{% static 'js/datatable.js' %}"></script>
    <script src="{% static 'js/ajax_csrf_setup.js' %}"></script>
    <script src="{% static 'js/refresh_submission.js' %}"></script>
{% endblock %}

app/templates/contests/base.html
{% extends 'pico/home.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title_block %}{{ contest_data.title }} Contest{% endblock %}

{% block head_block %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static 'css/timer_bar.css' %}">
{% endblock %}

{% block nav_block %}
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" id="main-navbar" role="navigation" style="margin-bottom: 0">
        <div class="navbar-inner">
            <div class="container">
                <div class="navbar-header pull-left">
                    <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i> PiCO</a>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-nav" style="margin:7px 0;">
                    <ul class="breadcrumb list-inline" style="margin: 0 7px;float:left;">
                        {% block breadcrumb %}
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Library</a></li>
                            <li class="active">Data</li>
                        {% endblock %}
                    </ul>
                    <!-- /.breadcrumb -->
                </ul>
                <!-- /.navbar-nav -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.navbar-inner -->
    </nav>
{% endblock %}

{% block content_block %}
    <div id="notificationModal"></div>
    <div id="getNotificationUrl" style="display: none;">{% url 'contests:show_notification'%}</div>
    <div id="closeNotificationUrl" style="display: none;">{% url 'contests:close_notification'%}</div>

    <!-- Time Remaining Bar -->
    {% if contest_data.contest_start != NULL and not is_past %}
        <div class="progress slower" id="timer_bar">
            <div class="time_remaining_div"><span class="time_remaining_text"></span></div>
            <div id="progress-slow" class="progress-bar progress-bar-striped active live_timer_div" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="height:170px; width:100%"></div>
        </div>
    {% endif %}

    {% if is_past %}
        <div class="well bs-component" style="text-align:center;">
            <h3>This is a past contest for viewing purposes only</h3>
            <p>(No new submissions or changes can be made)</p>
        </div>
    {% endif %}

    <div class="row text-center">
        <h1 style="font-weight: bold;">{{ contest_data.title }}</h1>
    </div>
    <br />
{% endblock %}

{% block foot_block %}
    {{ block.super }}

    <script src="{% static 'js/ajax_csrf_setup.js' %}"></script>
    <script src="{% static 'js/notification.js' %}"></script>

    {% if contest_data.contest_start != NULL or is_judge or is_creator %}
        <script type="text/javascript" src="{% static 'moment/moment.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/timer_bar.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lock_timer_bar.js' %}"></script>
        <script type="text/javascript">
            var contest_start = "{{ contest_data.contest_start | date:'Y-m-d H:i:s a' }}";
            var is_contest_started = contest_start != "None";
            var is_contest_ended = false;
            var contest_length = "{{ contest_data.contest_length }}";
            var home_url = "{% url 'contests:index' %}";

            loadTimerBar(contest_start, is_contest_started, is_contest_ended, contest_length, home_url);
            loadLockTimerBar(is_contest_started);
        </script>
        <script src="{% static 'js/refresh_scoreboard.js' %}"></script>
    {% endif %}
{% endblock %}

app/templates/contests/contest.html
{% extends 'contests/base.html' %}

{% load bootstrap3 %}
{% load staticfiles %}
{% load contest_extras %}

{% block title_block %}{{ block.super }}{% endblock %}

{% block head_block %}
    {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="active">{{ contest_data.title }}</li>
{% endblock %}

{% block content_block %}
    {{ block.super }}

    {% if is_judge or is_creator %}
        <div class="well bs-component">
            <span style="font-weight: bold;; float:left;">Judge Panel:</span>
            <div class="col-lg-8 col-lg-offset-2">
                <a class="btn-toolbar center-block">
                    <a href="{% url 'contests:contest_judge_submissions' contest_data.id %}" class="btn btn-default">View all submissions</a>
                </a>
                <span style="margin: 40px;"></span>
                <a class="btn-toolbar" style="float:right;">
                    {% if contest_data.contest_start == NULL %}
                        <a href="{% url 'contests:activate_contest' contest_data.id %}" class="btn btn-success">Activate Contest</a>
                    {% endif %}
                    {% if not is_past %}
                        <a href="{% url 'contests:edit_contest' contest_data.id %}" class="btn btn-primary">Edit Contest</a>
                    {% endif %}
                        <a href="{% url 'contests:delete_contest' contest_data.id %}" onclick="return confirm('Delete this contest?')" class="btn btn-danger">Delete Contest</a>
                </a>
            </div>
            <br />
        </div>
    {% endif %}

    {% if contest_data.contest_start != NULL or is_judge or is_creator %}
    <br />
        <a href="{% url 'contests:scoreboard' contest_data.id %}" class="btn btn-default">View Scoreboard</a>
    <br /><br />

    {% if current_team is not None %}
        <br /><a href="{% url 'contests:contest_submissions' contest_data.id current_team.id %}" class="btn btn-default">View my submissions</a><br />
    {% endif %}

    <br />
        <a href="{% url 'contests:problem_description' contest_data.id %}" class="btn btn-default">Problem Descriptions</a>
    <br /><br />

    <h3>Contest Problems:</h3>
    <div class="panel-group" id="accordion">
    {% for pair in problem_form_pairs %}
            {% if not is_participant %}
                <div class="panel panel-default">
            {% else %}
                <div class="panel panel-{{ color_states|index:forloop.counter }}">
            {% endif %}
                <!-- the data-parent attribute make sure only one panel is open at a time-->
                <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapse{{ forloop.counter }}">
                    <h4 class="panel-title">
                        <div style="display: table; width: 100%;">
                            <div class="col-sm-4" style="display: table-cell;">
                                Problem {{ forloop.counter }}
                            </div>
                            {% if is_participant %}
                            <div class="col-sm-4" style="display: table-cell;">
                                Submission Attempts: {{ submission_attempts|index:forloop.counter }}
                            </div>
                            <div class="col-sm-4" style="display: table-cell;">
                                Status: {{ submission_status|index:forloop.counter }}
                            </div>
                            {% endif %}
                        </div>
                    </h4>
                </div>
                <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
                    <ul class="list-group">
                        <li class="list-group-item">Description of Input
                            <div class="panel-body">
                                {{ pair.0.input_description }}
                            </div>
                        </li>
                        <li class="list-group-item">Description of Output
                            <div class="panel-body">
                                {{ pair.0.output_description }}
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div style="display: table; width: 100%;">
                                <div class="col-sm-6" style="display: table-cell;">Sample Input
                                    <div class="panel-body">
                                         <pre>{{ pair.0.sample_input|print_file_content }}</pre>
                                    </div>
                                </div>
                                <div class="col-sm-6" style="display: table-cell;">Sample Output
                                    <div class="panel-body">
                                         <pre>{{ pair.0.sample_output|print_file_content }}</pre>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <div class="panel-footer">
		      <form enctype="multipart/form-data" action="{% url 'contests:contest' contest_data.id %}" method="post">
			{% csrf_token %}
			Upload your file:
			{{ pair.1.as_p }}
			<input type="submit" value="Submit"/>
		      </form>
		    </div>
                </div>
            </div>
    {% endfor %}
    </div>
    {% else %}
        <div class="well bs-component" style="text-align:center;">
            <h3>This contest has not begun yet</h3>
            <br />
            <a href="{% url 'contests:index' %}" class="btn btn-primary">Return Home</a>
        </div>
    {% endif %}
{% endblock %}

app/templates/contests/create_contest.html
{% extends 'contests/contest_forms.html' %}

{% load staticfiles %}
{% load static %}
{% load bootstrap3 %}

{% block title_block %}Create Contest{% endblock %}

{% block head_block %}
    {{ block.super }}
{% endblock %}

{% block foot_block %}
    {{ block.super }}
{% endblock %}

app/templates/contests/error.html
<h1>{{ error_message }}</h1>

app/templates/contests/judge.html
{% extends 'contests/base.html' %}

{% load static %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load contest_extras %}

{% block title_block %}{{ block.super }}{% endblock %}

{% block head_block %}

    {{ block.super }}

    <!-- Diff table -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/diff.css' %}" />

    <!-- Fixed panel header -->
    <link rel="stylesheet" type="text/css" href="{% static 'fixed-panel-headers/css/style.css' %}" />

{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'contests:contest' contest_id=contest_data.id %}">{{ contest_data.title }}</a></li>
    <li><a href="{% url 'contests:contest_judge_submissions' contest_id=contest_data.id %}">Submissions</a></li>
    <li class="active">Judge</li>
{% endblock %}

{% block content_block %}
    {{ block.super }}

    <h2>Judging submission:</h2>
    <br />

    {% if is_judge %}
    <div class="panel panel-default panel-table fixed-header">
        <div class="panel-heading">
            <div class="row">
                <div class="col col-xs-4">
                    <h3 class="panel-title">Run ID: {{ submission.run_id }}</h3>
                </div>
                <div class="col col-xs-4">
                    <h3 class="panel-title">Team: {{ submission.team.name }} </h3>
                </div>
                <div class="col col-xs-4">
                    <h3 class="panel-title">State: {{ submission.get_state_display }}</h3>
                </div>
            </div>
            <div class="row" style="padding-top:8px">
                <div class="col-xs-12">
                    <button class="btn btn-default first-btn">first</button>
                    <button class="btn btn-default prev-btn">prev</button>
                    <button class="btn btn-default next-btn">next</button>
                    <button class="btn btn-default last-btn">last</button>


                    <span class="checkbox" style="display:inline-block;margin-left:20px;">
                        <label><input class="checkbox-whitespace" type="checkbox" checked>Whitespace</label>
                    </span>
                    <span class="checkbox" style="display:inline-block;margin-left:20px;">
                        <label><input class="checkbox-emptylines" type="checkbox" checked>Empty lines</label>
                    </span>

                    <span style="display:inline-block;margin-left:20px;">
                        <label>Differences:</label> <span class="num-changes">{{numChanges}}</span> lines
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-body">
	<div>
		{{ diff_table|safe }}

    	</div>
            </div>
            <div class="panel-footer">
                <form class="form-inline" enctype="multipart/form-data" action="{% url 'contests:contest_judge' contest_data.id submission.run_id%}" method="post">
                    {% csrf_token %}
                    <label>Result&nbsp;</label>
                    {% bootstrap_form form layout='inline' %}
                    <input class="pull-right btn btn-default" type="submit" value="Submit" name="submit"/>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block foot_block %}
    
    <script type=text/javascript>
        var lock_timer_bar = false;
    </script>

    {{ block.super }}

    <!-- Fixed Panel Header -->
    <script type="text/javascript" src="{% static 'fixed-panel-headers/js/scrollHeadings.js' %}"></script>

    <script type="text/javascript">

        ////////////////////////
        // Diff table nav bar //
        ////////////////////////

        var numChanges = {{ numChanges }};
        
        var cur = 1;
        var url = document.location.toString()
        var i = url.indexOf("#");
        if (i != -1) {
            cur = parseInt(url.substring(i+1));
            $(document).ready(function() { goToAnchor(cur); });
        }
        if (cur > numChanges || Number.isNaN(cur)) {
            cur = 0;
            document.location = url.substring(0,i);
        }

        var first = 1;
        var prev = cur-1;
        var next = cur+1;
        var last = numChanges;

        function goToAnchor(anchor) {
            var loc = document.location.toString().split('#')[0];
            document.location = loc + '#' + anchor;
            window.scrollBy(0, $('.panel.fixed-header .panel-heading').first().outerHeight() * -1);

            cur = anchor;
            prev = anchor-1;
            next = anchor+1;

            $('.first-btn').prop('disabled', numChanges==0||cur==first);
            $('.last-btn').prop('disabled', numChanges==0||cur==last);
            $('.prev-btn').prop('disabled', prev<first);
            $('.next-btn').prop('disabled', next>last);
        }

        $(document).on('click', '.first-btn', function() { goToAnchor(first); });
        $(document).on('click', '.last-btn', function() { goToAnchor(last); });
        $(document).on('click', '.prev-btn', function() { goToAnchor(prev); });
        $(document).on('click', '.next-btn', function() { goToAnchor(next); });

        $(document).ready(function(){
            $('.first-btn').prop('disabled', numChanges==0||cur==first);
            $('.last-btn').prop('disabled', numChanges==0||cur==last);
            $('.prev-btn').prop('disabled', prev<first);
            $('.next-btn').prop('disabled', next>last);
        });

        ///////////////////////
        // Intelligent diffs //
        ///////////////////////

        function resetDiffBackgrounds() {
            $('.diff-text:not(:has(.diff-add:not(.diff-none),.diff-del:not(.diff-none),.diff-chg:not(.diff-none)))').addClass('diff-none');
            $('.diff-text:has(.diff-add:not(.diff-none),.diff-del:not(.diff-none),.diff-chg:not(.diff-none))').removeClass('diff-none');
        };

        function syncNumChanges() {
            var numChanges = $('.diff-table tr:has(.diff-text:has(.diff-add:not(.diff-none),.diff-del:not(.diff-none),.diff-chg:not(.diff-none)))').length;
            $('.num-changes').text(numChanges);
            return numChanges;
        };

        $(document).on('change', '.checkbox-whitespace', function() {
            $('.checkbox-whitespace').prop('checked', this.checked);
            if (this.checked) {
                $('.diff-whitespace').removeClass('diff-none').closest('.diff-text').removeClass('diff-none');
            } else {
                $('.diff-whitespace').addClass('diff-none');
                resetDiffBackgrounds();
            }
            syncNumChanges();
        });
        $(document).on('change', '.checkbox-emptylines', function() {
            $('.checkbox-emptylines').prop('checked', this.checked);
            if (this.checked) {
                $('.diff-emptyline').removeClass('diff-none').closest('.diff-text').removeClass('diff-none');
            } else {
                $('.diff-emptyline').addClass('diff-none');
                resetDiffBackgrounds();
            }
            syncNumChanges();
        });
        syncNumChanges();

    </script>
{% endblock %}