app/contests/urls.py

from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create_contest$', views.createContest, name='create_contest'),
	url(r'^edit/(?P<contest_id>\d+)/$', views.editContest, name='edit_contest'),
	url(r'^delete/(?P<contest_id>\d+)/$', views.deleteContest, name='delete_contest'),
	url(r'^activate/(?P<contest_id>\d+)/$', views.activateContest, name='activate_contest'),
	url(r'^create_template$', views.createTemplate, name='create_template'),
	url(r'^scoreboard/$', views.scoreboard, name='scoreboard'),
	url(r'^contest/(?P<contest_id>\d+)/$', views.displayContest, name='contest'),
	url(r'^contest/(?P<contest_id>\d+)/problemDescription$', views.displayProblemDescription, name='problem_description'),
	url(r'^contest/(?P<contest_id>\d+)/scoreboard$', views.scoreboard, name='scoreboard'),
	url(r'^contest/(?P<contest_id>\d+)/judge$', views.displayAllSubmissions, name='contest_judge_submissions'),
	url(r'^contest/(?P<contest_id>\d+)/judge/(?P<run_id>\d+)/$', views.displayJudge, name='contest_judge'),
	url(r'^contest/(?P<contest_id>\d+)/(?P<team_id>\d+)/submissions$',
		views.displayMySubmissions, name='contest_submissions'),
	url(r'^api/get_notification/$', views.show_notification, name='show_notification'),
	url(r'^api/close_notification/$', views.close_notification, name='close_notification'),
	url(r'^api/refresh_submission/$', views.refresh_submission, name='refresh_submission'),
	url(r'^api/refresh_scoreboard/$', views.refresh_scoreboard, name='refresh_scoreboard'),
]

app/pico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^teams/', include('teams.urls', namespace='teams')),
	url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
	url(r'^$', views.index, name='index'),
	url(r'^home$', views.home, name='home'),
] + static(settings.MEDIA_URL.replace('/pico',''), document_root=settings.MEDIA_ROOT) # works on server

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # works locally

app/users/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .forms import EmailValidationOnForgotPassword

from . import views

urlpatterns = [
	url(r'^$', views.view, name='index'),
	url(r'^(?P<user_id>[0-9]*)/$', views.view, name='view'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^edit$', views.edit, name='edit'),
	url(r'^settings$', views.settings, name='settings'),
	url(r'^passwordchange$', views.password_change, name='password_change'),
	url(r'^password/reset/$', password_reset,
		{'template_name': 'users/password_reset/password_reset_form.html',
		 'password_reset_form':EmailValidationOnForgotPassword,
		'email_template_name': 'users/password_reset/password_reset_email.html',
		'post_reset_redirect' : reverse_lazy('users:password_reset_done')},
		name="password_reset"),
	url(r'^password/reset/done/$', password_reset_done,
		{'template_name': 'users/password_reset/password_reset_done.html'},
		name='password_reset_done'),
	url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		password_reset_confirm,
		{'template_name': 'users/password_reset/password_reset_confirm.html',
		'post_reset_redirect' : reverse_lazy('users:password_done')},
		name='password_reset_confirm'),
	url(r'^password/done/$',
		password_reset_complete,
		{'template_name': 'users/password_reset/password_reset_complete.html'},
		name='password_done'),
	url(r'^autocomplete$', views.UserAutocomplete.as_view(), name='autocomplete'),
]

app/pico/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required

from common.decorators import anonymous_required
from contests.models import Contest
from users.forms import LoginForm, UserForm

@anonymous_required
def index(request):
    return render(
        request,
        'pico/index.html',
        {'login_form': LoginForm(), 'user_form': UserForm()})

@login_required
def home(request):
    return redirect(reverse('contests:index'))
    # return render(request, 'pico/home.html', {})

app/templates/pico/_construction.html
{% extends 'pico/home.html' %}

{% block content_block %}
<h1 class="page-header">Under Construction</h1>
<p>This portion of the site is currently under construction. Come back later.</p>
{% endblock %}

app/templates/pico/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}PiCO{% endblock %}

{% block head_block %}

    <!-- Navigation CSS -->
    <link rel="stylesheet" href="{% static 'css/navigation.css' %}">

{% endblock %}

{% block body_block %}

    {% block nav_block %}

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" id="main-navbar" role="navigation" style="margin-bottom: 0">
            <div class="navbar-inner">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i> PiCO</a>
                    </div>
                    <!-- /.navbar-header -->

                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-left">
                            <li><a href="{% url 'contests:index' %}"><i class="fa fa-trophy" aria-hidden="true"></i> Contests</a></li>
                            <li><a href="{% url 'teams:index' %}"><i class="fa fa-users" aria-hidden="true"></i> Teams</a></li>
                            <li><a href="{% url 'stats:index' %}"><i class="fa fa-bar-chart" aria-hidden="true"></i> Statistics</a></li>  
                        </ul>

                        <ul class="nav navbar-nav navbar-right navbar-top-links">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-alerts">
                                    {% if request.user.alerts.all %}
                                        {% for alert in request.user.alerts.all %}
                                            {% if not forloop.first %}<li class="divider"></li>{% endif %}
                                            <li>
                                                <a href="{{ alert.href }}">
                                                    <div>
                                                        {% if alert.subject %}<strong>{{ alert.subject }}</strong>{% endif %}
                                                        <span class="pull-right text-muted small" style="padding-left:8px;">4 minutes</span>
                                                    </div>
                                                    <div>
                                                        {% if not alert.subject and not alert.body %}
                                                            <em>No content</em>
                                                        {% else %}
                                                            {{ alert.body|safe }}
                                                        {% endif %}
                                                    </div>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    {% else %}
                                        <li class="text-center">No alerts</li>
                                    {% endif %}
                                </ul>
                                <!-- /.dropdown-alerts -->
                            </li>
                            <!-- /.dropdown -->
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right dropdown-user">
                                    <li><a href="{% url 'users:view' user_id=request.user.id %}"><i class="fa fa-user fa-fw"></i> My Profile</a></li>
                                    <li><a href="{% url 'users:settings' %}"><i class="fa fa-gear fa-fw"></i> Settings</a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'users:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
                                </ul>
                                <!-- /.dropdown-user -->
                            </li>
                            <!-- /.dropdown -->
                        </ul>
                        <!-- /.navbar-top-links -->
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </div>
            <!-- /.navbar-inner -->
        </nav>

    {% endblock %}

    <div class="spacer" style="margin-top:15px"></div>

    <div class="container" id="content">
        {% block content_block %}
            <div class="row col-md-5" id="active-contests">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Active Contests</h3>
                    </div>
                    {% if active_contests %}
                        <div class="list-group">
                            {% for contest in active_contests %}
                                <a href="{% url 'contests:contest' contest.id %}" class="list-group-item">
                                    <strong>{{ contest.title }}:</strong> {{ contest.time_remaining }}
                                </a>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="list-group"><div class="list-group-item">No active contests</div></div>
                    {% endif %}
                </div>
                <!-- /.panel -->
            </div>
            <!-- /#active-contests -->

        {% endblock %}
    </div>
    <!-- /.container -->

{% endblock %}

{% block foot_block %}

    <!-- Navigation JavaScript -->
    <script src="{% static 'js/navigation.js' %}"></script>

{% endblock %}

app/templates/pico/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block head_block %}
    <style>
        body {
            background: #fff url("{% static 'images/background.jpg' %}") no-repeat center center fixed; 
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        #logo-circle {
            width: 100px;
            height: 100px;
            margin: 30px;
            margin-left: auto;
            margin-right: auto;
            display: table;
            
            background: rgba(20,30,34,0.7);
            border-radius: 100%;
            border: 4px solid rgba(20,30,34,0.9);
        }
        #logo {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }
        #logo a,
        #logo a:hover,
        #logo a:focus {
            color: #f3f3f3;
            font-size: 24px;
            font-weight: bold;
        }
        .form-panel {
            background: rgba(20,30,34,0.7);
            color: #f3f3f3;
            margin-top:30px;
            margin-left: auto;
            margin-right: auto;
            padding: 0;
            width: 408px;
        }
        .form-panel .nav-pills {
            margin: 0;
            padding: 0;
        }
        .form-panel .nav-pills > li {
            width: 50%;
            margin: 0;
        }
        .form-panel .nav-pills a {
            color: #f3f3f3;
            font-size: 16px;
            font-weight: bold;
            text-align: center;
        }
        .form-panel .nav-pills a:hover,
        .form-panel .nav-pills a:focus {
            color: black;
            outline: none;
        }
        .form-panel .nav-pills .active a,
        .form-panel .nav-pills .active a:hover,
        .form-panel .nav-pills .active a:focus {
            background: rgba(20,30,34,0.9);
            outline: none;
        }
        .form-panel .nav-pills > li > a {
            border-radius: 0;
            color: #f3f3f3;
        }
        .form-panel .tab-content {
            background: rgba(20,30,34,0.9);
            margin: 0;
            padding: 15px;
        }
        .form-panel .tab-content .control-label {
            padding-right: 0;
        }
        .form-panel .form-buttons {
            text-align: right;
        }
        .footer {
            color: white;
        }
        .hr-faded {
            background-color: #f3f3f3;
            background-image: -webkit-gradient(linear, left top, right top, from(rgba(0, 0, 0, 0)), to(#f3f3f3), from(#f3f3f3), to(rgba(0, 0, 0, 0)));
            background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0), #f3f3f3, rgba(0, 0, 0, 0));
            background-image: -moz-linear-gradient(left, rgba(0, 0, 0, 0), #f3f3f3, rgba(0, 0, 0, 0));
            background-image: -ms-linear-gradient(left, rgba(0, 0, 0, 0), #f3f3f3, rgba(0, 0, 0, 0));
            background-image: -o-linear-gradient(left, rgba(0, 0, 0, 0), #f3f3f3, rgba(0, 0, 0, 0));
            width: 90%;
            height: 1px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 10px;
            margin-bottom: 10px;
            background-color: transparent; /* add this line after the mixin call */
        }
    </style>
{% endblock %}

{% block body_block %}
    <div id="logo-circle"><div id="logo"><a href="{% url 'index' %}">PiCO</a></div></div>

    <div class="container form-panel">
        {% block form_block %}
            <ul class="nav nav-pills">
                <li class="active">
                    <a href="#login" data-toggle="tab">Login</a>
                </li>
                <li>
                    <a href="#register" data-toggle="tab">Register</a>
                </li>
            </ul>

            <div class="tab-content clearfix">
                <div class="tab-pane active" id="login">
                    <form class="form form-horizontal" id="login_form" method="post" action="{% url 'users:login' %}">
                        {% csrf_token %}
                        {% bootstrap_form login_form layout='horizontal' %}
                        
                        {% buttons layout='horizontal' %}
                            {% bootstrap_button 'Submit' 'submit' %}
                            {% url 'users:password_reset' as password_reset_url %}
                            {% bootstrap_button 'Forgot password' 'link' href=password_reset_url %}
                        {% endbuttons %}
                    </form>
                </div>
                <div class="tab-pane" id="register">
                    <form class="form form-horizontal" id="user_form" method="post" action="{% url 'users:register' %}"
                            enctype="multipart/form-data">

                        {% csrf_token %}
                        {% bootstrap_form user_form layout='horizontal' %}

                        {% buttons layout='horizontal' %}
                            {% bootstrap_button 'Submit' 'submit' %}
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        {% endblock %}
    </div>
{% endblock %}

{% block foot_block %}
<script>
$('a[data-toggle="tab"]').on('show.bs.tab', function(e) {
    localStorage.setItem('activeTab', $(e.target).attr('href'));
});
var activeTab = localStorage.getItem('activeTab');
if (activeTab) {
    $('.nav-pills a[href="' + activeTab + '"]').tab('show');
}
</script>
{% endblock %}